services:
 minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 66668888
    command: server /data --console-address ":9001"

volumes:
  redis_data:
    driver: local
  minio_data:
    driver: local

